<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="im"%>

<!-- from modEncode -->
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<html:xhtml/>

<div class="body">

<div align="center">

<im:boxarea title="Data" stylename="plainbox"><p><fmt:message key="dataCategories.intro"/></p></im:boxarea>
<table cellpadding="0" cellspacing="0" border="0" class="dbsources">
  <tr>
    <th>Data Category</th>
    <th>Organism</th>
    <th>Data</th>
    <th>Source</th>
    <th>PubMed</th>
    <th>Note</th>
  </tr>

<!-- toxoCore -->
  <tr>
    <td class="leftcol"><html:link action="/projects.do"> <p><img src="model/images/toxoCore.png" /></p> <p> toxoCore </p></html:link></td>
    <td> <i>T. gondii</i> </td>
    <td> toxoCore Data </td>
    <td> &nbsp;</td>
    <td> &nbsp;</td>
    <td> toxoCore is a central data repository for both raw and processed epigenomic data and its metadata generated by <i>T. gondii</i> research community.</td>
  </tr>
  
<!-- Genomics -->
  <tr>
    <td class="leftcol"><html:link action="/aspect?name=Genomics"> <p><img src="model/images/genomics.gif" /></p> <p> Genomics </p></html:link></td>
    <td> <i>T. gondii</i> </td>
    <td> Genome annotation </td>
    <td> <a href="http://toxodb.org" target="_new" class="extlink">ToxoDB.org</a></td>
    <td> Gajria et al - <a href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&dopt=Abstract&list_uids=18003657" target="_new" class="extlink">PubMed: 18003657</a></td>
    <td> &nbsp;</td>
  </tr>

<!-- Proteins -->
  <tr>
    <td class="leftcol"><html:link action="/aspect?name=Proteins"> <p><img src="model/images/proteins.png" /></p> <p> Proteins </p></html:link></td>
    <td> <i>T. gondii</i> </td>
    <td> Protein annotation</td>
    <td> <a href="http://www.ebi.uniprot.org/index.shtml" target="_new" class="extlink">UniProt</a></td>
    <td> UniProt Consortium - <a href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&dopt=Abstract&list_uids=17142230" target="_new" class="extlink">PubMed: 17142230</a></td>
    <td> &nbsp;</td>
  </tr>

<!-- Ontologies -->
  <tr>
    <td class="leftcol"><html:link action="/aspect?name=Functions"> <p><img src="model/images/geneOntology.png" /></p> <p> Gene Ontology </p></html:link></td>
    <td> <i>T. gondii</i> </td>
    <td> GO annotation </td>
    <td> <a href="http://www.geneontology.org" target="_new" class="extlink">Gene Ontology Site</a></td>
    <td> Gene Ontology Consortium - <a href="http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&db=PubMed&dopt=Abstract&list_uids= 10802651" target="_new" class="extlink">PubMed:10802651</a></td>
    <td> &nbsp;</td>
  </tr>

<!-- Literatures -->
  <tr>
    <td class="leftcol"><html:link action="/aspect?name=Literature"> <p><img src="model/images/book.png" /></p> <p> Literature</p></html:link></td>
    <td> <i>T. gondii</i> </td>
    <td> Gene versus publications</td>
    <td> <a href="http://www.ncbi.nlm.nih.gov" target="_new" class="extlink">NCBI</a></td>
    <td> &nbsp;</td>
    <td> &nbsp;</td>
  </tr>
  
</table>
</div>
